name: Build and Deploy

on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build Docker image
      run: docker build . -t nlp_model_app

    - name: Run Docker container
      run: |
        docker stop nlp_model_app_container || true
        docker rm nlp_model_app_container || true
        docker run -d -p 8000:8000 --name nlp_model_app_container nlp_model_app
